name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build do projeto
        run: echo "Build realizado com sucesso"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Testes automatizados
        run: echo "Testes executados com sucesso"

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Empacotar com Maven
        run: mvn package

  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Deploy simulação
        run: echo "Deploy realizado com sucesso"
