name: Hello Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
jobs:
  hello_job:
    runs-on: ubuntu-latest
    steps:
      - name: Exibe mensagem de sucesso
        run: echo "Pipeline iniciado com sucesso"
